# Generated by Django 3.0.3 on 2021-05-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passengeru', to=settings.AUTH_USER_MODEL),
        ),
    ]
