# Generated by Django 3.0.3 on 2021-05-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0005_auto_20210504_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('TSHO', 'TSHO'), ('Mechanic', 'Mechanic'), ('Driver', 'Driver'), ('StoreManager', 'Store Manager'), ('SchoolDean', 'School Dean'), ('DepartmentHead', 'Department Head'), ('VicePresident', 'Vice President')], max_length=200),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('house_no', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
