# Generated by Django 3.0.3 on 2021-05-22 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0006_auto_20210504_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EPCE', 'EPCE'), ('MCE', 'MCE'), ('MSE', 'MSE'), ('CHE', 'CHE'), ('CE', 'CE'), ('WRE', 'WRE'), ('ARCH', 'ARCH'), ('Maths', 'Maths'), ('Pysics', 'Pysics'), ('Chemistry', 'Chemistry'), ('Bio', 'Bio'), ('Geology', 'Geology')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='school',
            field=models.CharField(choices=[('SOEEC', 'SOEEC'), ('SOMCME', 'SOMCME'), ('SOCEA', 'SOCEA'), ('SOANS', 'SOANS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
