# Generated by Django 3.0.3 on 2021-05-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0007_auto_20210522_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='department',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='school',
        ),
    ]
