# Generated by Django 3.0.3 on 2021-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0008_auto_20210522_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='sex',
        ),
        migrations.AddField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200, null=True),
        ),
    ]
