# Generated by Django 3.0.3 on 2021-05-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0010_transportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='passenger_numbers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='reason',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
