# Generated by Django 3.0.3 on 2021-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0011_auto_20210522_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='status2',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
