# Generated by Django 3.0.3 on 2021-05-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0012_transportrequest_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='status3',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
