# Generated by Django 3.0.3 on 2021-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0013_transportrequest_status3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportrequest',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EPCE', 'EPCE'), ('MCE', 'MCE'), ('MSE', 'MSE'), ('CHE', 'CHE'), ('CE', 'CE'), ('WRE', 'WRE'), ('ARCH', 'ARCH'), ('Maths', 'Maths'), ('Pysics', 'Pysics'), ('Chemistry', 'Chemistry'), ('Bio', 'Bio'), ('Geology', 'Geology')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(blank=True, choices=[('SOEEC', 'SOEEC'), ('SOMCME', 'SOMCME'), ('SOCEA', 'SOCEA'), ('SOANS', 'SOANS')], max_length=200, null=True),
        ),
    ]
