# Generated by Django 3.0.3 on 2021-05-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0014_auto_20210523_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportrequest',
            old_name='sender',
            new_name='user',
        ),
    ]
