# Generated by Django 3.0.3 on 2021-06-02 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0015_auto_20210524_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('minibus', 'minibus'), ('bus', 'bus'), ('kobra', 'kobra'), ('ambulance', 'ambulance')], max_length=200)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Not active', 'Not active'), ('Active', 'Active')], default='Active', max_length=200)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
