# Generated by Django 3.0.3 on 2021-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0016_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Not Occupied', 'Not Occupied'), ('Occupied', 'Occupied')], default='Not Occupied', max_length=200),
        ),
    ]
