# Generated by Django 3.0.3 on 2021-06-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0019_auto_20210602_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedvehicle',
            old_name='My_vehicle',
            new_name='my_vehicle',
        ),
        migrations.AddField(
            model_name='approverequest',
            name='time',
            field=models.CharField(default='06:00am', max_length=200),
        ),
        migrations.AlterField(
            model_name='approverequest',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trequest.AssignedVehicle'),
        ),
    ]
