# Generated by Django 3.0.3 on 2021-06-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0020_auto_20210602_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Trequest.TransportRequest'),
        ),
        migrations.AlterField(
            model_name='approverequest',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Trequest.AssignedVehicle'),
        ),
    ]
