# Generated by Django 3.0.3 on 2021-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0021_auto_20210602_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200),
        ),
    ]
