# Generated by Django 3.2.4 on 2021-06-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0024_rename_user_transportrequest_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='Trequest.myuser'),
            preserve_default=False,
        ),
    ]
