# Generated by Django 3.2.4 on 2021-06-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0025_alter_transportrequest_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approverequest',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Trequest.vehicle'),
        ),
        migrations.DeleteModel(
            name='AssignedVehicle',
        ),
    ]
