# Generated by Django 3.2.4 on 2021-06-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0027_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='adder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add', to='Trequest.myuser'),
            preserve_default=False,
        ),
    ]
