# Generated by Django 3.2.4 on 2021-07-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0028_vehicle_adder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Passenger',
            new_name='Profile',
        ),
    ]
