# Generated by Django 3.2.5 on 2021-07-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0034_transportrequest_list_of_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='currently',
            field=models.CharField(choices=[('Outside', 'Outside'), ('Inside', 'Inside')], default='Inside', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trequest.driver'),
        ),
    ]
