# Generated by Django 3.2.5 on 2021-08-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0040_auto_20210801_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='sender_id',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trequest', to='Trequest.transportrequest'),
        ),
    ]
