# Generated by Django 3.1.7 on 2021-08-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0041_auto_20210803_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverevaluation',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_name', to='Trequest.transportrequest'),
        ),
    ]
