# Generated by Django 3.2.5 on 2021-08-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0041_auto_20210801_2219'),
        ('Trequest', '0042_driverevaluation_trip'),
    ]

    operations = [
    ]
