# Generated by Django 3.2.5 on 2021-08-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0036_historicalmaterial'),
        ('Trequest', '0044_auto_20210803_1031'),
    ]

    operations = [
    ]
