# Generated by Django 3.2.5 on 2021-08-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0045_merge_0036_historicalmaterial_0044_auto_20210803_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalMaterial',
        ),
    ]
