# Generated by Django 3.2.5 on 2021-08-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0046_delete_historicalmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverequest',
            name='from_who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to='Trequest.transportrequest'),
        ),
    ]
