# Generated by Django 3.1.7 on 2021-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0046_auto_20210807_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='log_object',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='instances',
            field=models.CharField(max_length=500),
        ),
    ]
