# Generated by Django 3.2.5 on 2021-08-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0048_auto_20210806_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='condition',
            field=models.CharField(choices=[('Reusable', 'reusable'), ('Usable', 'usable')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200),
        ),
    ]
