# Generated by Django 3.2.5 on 2021-08-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0049_auto_20210808_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='condition',
            field=models.CharField(blank=True, choices=[('Reusable', 'reusable'), ('Usable', 'usable')], max_length=200, null=True),
        ),
    ]
