# Generated by Django 3.2.5 on 2021-08-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0050_materialrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='old_material_name',
        ),
    ]
