# Generated by Django 3.2.5 on 2021-08-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0050_feedback'),
        ('Trequest', '0051_remove_materialrequest_old_material_name'),
    ]

    operations = [
    ]
