# Generated by Django 3.2.5 on 2021-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0053_auto_20210810_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=200),
        ),
    ]
