# Generated by Django 3.2.5 on 2021-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0054_auto_20210811_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
