# Generated by Django 3.2.5 on 2021-08-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0057_auto_20210811_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='sent_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service_type',
            field=models.CharField(choices=[('Regular Transport Service', 'Regular Transport Service'), ('Field Transport Service', 'Field Transport Service'), ('Educational Transport Service', 'Educational Transport Service')], max_length=200),
        ),
    ]
