# Generated by Django 3.2.5 on 2021-08-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0058_auto_20210815_1104'),
        ('Trequest', '0058_auto_20210817_1456'),
    ]

    operations = [
    ]
