# Generated by Django 3.2.5 on 2021-08-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0050_auto_20210809_0826'),
        ('Trequest', '0059_auto_20210819_1447'),
    ]

    operations = [
    ]
