# Generated by Django 3.2.5 on 2021-08-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0059_auto_20210819_1447'),
        ('Trequest', '0059_merge_0058_auto_20210815_1104_0058_auto_20210817_1456'),
    ]

    operations = [
    ]
