# Generated by Django 3.2.5 on 2021-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0061_auto_20210819_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
