# Generated by Django 3.2.5 on 2021-08-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0062_alter_vehicle_vehicle_type'),
        ('Trequest', '0066_auto_20210824_0029'),
    ]

    operations = [
    ]
