# Generated by Django 3.2.5 on 2021-08-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0068_auto_20210824_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='new_material_name',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='vehicle_model',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialRequest',
        ),
    ]
