# Generated by Django 3.2.5 on 2021-08-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0069_auto_20210824_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveRequest',
        ),
    ]
