# Generated by Django 3.2.5 on 2021-08-25 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0070_delete_approverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : 0987654321 or +251987654321 up to 15 digits allowed', regex='/^(09|\\+2519)\\d{8}$/')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('TSHO', 'TSHO'), ('Mechanic', 'Mechanic'), ('Driver', 'Driver'), ('StoreManager', 'Store Manager'), ('SchoolDean', 'School Dean'), ('DepartmentHead', 'Department Head'), ('VicePresident', 'Vice President'), ('Admin', 'Admin')], max_length=200),
        ),
    ]
