# Generated by Django 3.2.5 on 2021-08-25 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trequest', '0071_auto_20210825_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : 0987654321 or +251987654321 up to 15 digits allowed', regex='^(09|\\+2519)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
