# Generated by Django 3.2.5 on 2021-08-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trequest', '0069_auto_20210824_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_material_model', models.CharField(max_length=200)),
                ('quantity_of_new', models.PositiveIntegerField()),
                ('quantity_of_old', models.PositiveIntegerField()),
                ('old_material_model', models.CharField(max_length=200)),
                ('condition', models.CharField(blank=True, choices=[('Reusable', 'reusable'), ('Usable', 'usable')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('new_material_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_material', to='MaterialApp.material')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Trequest.vehicle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
