# Generated by Django 3.2.5 on 2021-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
